### ISSUE TITLE
Failed to resolve: com.ryanharter.auto.value:auto-value-moshi-runtime:1.0.0

### ISSUE THREAD

**Issue by wizlif** [rharter/auto-value-moshi#181] opened 2021-02-20 21:23 UTC
Adding the Gradle download instructions fails with the error above during Gradle sync

`Failed to resolve: com.ryanharter.auto.value:auto-value-moshi-runtime:1.0.0`

**Comment by ZacSweers** [comment] 2021-02-20 21:41
Dupe of #164, please check existing issues first

**Closed as completed by ZacSweers** 2021-02-20 21:41 UTC
