### ISSUE TITLE
MoshiAdapterFactory uses the first static method with a generic return type

### ISSUE THREAD

**Issue by ansman** [rharter/auto-value-moshi#86] opened 2017-03-08 08:25 UTC
The following code demonstrates the problem:

```java
@AutoValue
public abstract class MyObject {
    public abstract String name();

    public static List<String> someOtherMethod() {
        return null;
    }

    @NonNull
    public static JsonAdapter<MyObject> jsonAdapter(@NonNull Moshi moshi) {
        return new AutoValue_MyObject.MoshiJsonAdapter(moshi);
    }
}
```

```java
@MoshiAdapterFactory
public abstract class MyAdapterFactory implements JsonAdapter.Factory {
    public static JsonAdapter.Factory create() {
        return new AutoValueMoshi_MyAdapterFactory();
    }
}
```

This will produce the following factory:
```java
public final class AutoValueMoshi_MyAdapterFactory extends MyAdapterFactory {
  @Override
  public JsonAdapter<?> create(Type type, Set<? extends Annotation> annotations, Moshi moshi) {
    if (!annotations.isEmpty()) return null;
    if (type.equals(MyObject.class)) {
      return MyObject.someOtherMethod(moshi);
    }
    return null;
  }
}
```

**Comment by JakeWharton** [comment] 2017-03-08 16:30
Dupe of #82

**Closed as completed** 2017-03-08 16:34 UTC
