### ISSUE TITLE
Nullsafe adapter not writing null values

### ISSUE THREAD

**Issue by Meisolsson** [rharter/auto-value-moshi#126] opened 2019-02-12 14:09 UTC
When unsetting a value with a request the API I'm talking to requires the value which is being unset to be `null`. I have a nullsafe adapter factory and the value is nullable but when the values are being written the null value is skipped. I'm guessing this is expected behaviour but I'd like to know if I can skip this for certain values (or all).

**Comment by ZacSweers** [comment] 2019-04-27 06:30
if I'm reading this correctly, this is normal behavior and you need to enable `serializeNulls()` in the writer that's passed in

```kotlin
val writer = JsonWriter.of(...)
writer.serializeNulls()

moshi.adapter(...)
    .toJson(writer, object)
```

**Comment by rharter** [comment] 2019-05-20 15:19
I'm closing this as it's not an auto-value-moshi issue.  If you find an issue relating to this with AVM feel free to reopen.

**Closed as completed by rharter** 2019-05-20 15:19 UTC

**Comment by Knotworking** [comment] 2020-10-19 13:48
We have the same use case as the original poster and from our investigations this does seem to be an auto-value-moshi issue.

[Here is a sample project](https://github.com/cleemansen/avm-nullable) we've written to demonstrate the issue. Please see the [SerializeTest](https://github.com/cleemansen/avm-nullable/blob/main/src/test/kotlin/SerializeTest.kt) test class.

We have tried the proposed solution above, but the problem is that within the generated `toJson` method the writer (which has [serializeNulls](https://github.com/cleemansen/avm-nullable/blob/1d46bb174e75108f9764951413728c52d0c478e0/src/main/kotlin/Issue.kt#L29) = true) is only accessed within a `field != null` if statement, so the nullable field is never added to the json object to be written.

[This](https://github.com/rharter/auto-value-moshi/blob/main/auto-value-moshi-extension/src/main/java/com/ryanharter/auto/value/moshi/AutoValueMoshiExtension.java#L574) looks as if it’s the cause of our issue.
